version: '3'
services:
    fmd:
        build: .
        container_name: fmd
        ports:
         - 127.0.0.1:8080:8080
        volumes:
            - './data:/fmd/objectbox/'
        restart: unless-stopped
